name: Feature Request
description: Suggest an improvement or new feature
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
      placeholder: I want to... but currently...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should it work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you've thought about

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - Safety rules
        - Configuration
        - Performance
        - Audit logging
        - Advertising blocker
        - Documentation
        - Other
